server:
  port: 18090
feign:
  sentinel:
    enabled: true
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.188.18:3306/guli_cart?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: cerosg
  redis:
    host: 121.196.26.42
    password: cerosg
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  # SpringTask线程池配置
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 100
        max-size: 500
        keep-alive: 60s
        queue-capacity: 1000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 100
auth:
  jwt:
    # \u516C\u94A5\u8DEF\u5F84
    pubKeyPath: F:\\project\\GuliMall\\gmall\\RSA\\rsa.pub
    cookieName: GMALL_TOKEN
    userKeyName: user_key
