server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      x-forwarded:
        host-enabled: true
      routes:
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        # 搜索页路由
        - id: search-route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        # 首页路由1
        - id: index-route1
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com,gmall.com
        # 首页路由2
        - id: index-route2
          uri: lb://index-service
          predicates:
            - Path=/index/**
          filter:
            -
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        # 单点登录路由
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        # 购物车
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
auth:
  jwt:
    # 公钥路径
    pubKeyPath: F:\\project\\GuliMall\\gmall\\RSA\\rsa.pub
    cookieName: GMALL_TOKEN