server:
  port: 18081

feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto

# MQ生产者属性配置
spring:
  rabbitmq:
    host: 192.168.188.18
    virtual-host: /cerosg
    username: Cerosg
    password: cerosg
    # 确认消息是否到达交换机：simple-同步确认；correlated-异步确认。
    publisher-confirm-type: correlated
    # 确认消息是否到达队列
    publisher-returns: true